<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43171" started-at="2018-11-20T06:59:36Z" finished-at="2018-11-20T07:00:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43171" started-at="2018-11-20T06:59:36Z" finished-at="2018-11-20T07:00:20Z">
      <class name="com.lala.test.CancelOrderTest">
        <test-method status="PASS" signature="suitelalaTestNGTest()[pri:0, instance:com.lala.test.CancelOrderTest@6d00a15d]" name="suitelalaTestNGTest" is-config="true" duration-ms="6" started-at="2018-11-20T12:29:36Z" finished-at="2018-11-20T12:29:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suitelalaTestNGTest -->
        <test-method status="FAIL" signature="verifyCancelOrder()[pri:6, instance:com.lala.test.CancelOrderTest@6d00a15d]" name="verifyCancelOrder" duration-ms="43158" started-at="2018-11-20T12:29:36Z" finished-at="2018-11-20T12:30:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.lala.test.CancelOrderTest.verifyCancelOrder(CancelOrderTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCancelOrder -->
      </class> <!-- com.lala.test.CancelOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
